[package]
name = "falcon-server"
version.workspace = true
edition.workspace = true

[dependencies]
falcon-core = { workspace = true }
falcon-facade = { workspace = true }
falcon-persistence = { workspace = true }
ahash = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
