[package]
name = "shrikedb-facade"
version.workspace = true
edition.workspace = true

[dependencies]
shrikedb-core = { workspace = true }
bytes = { workspace = true }
itoa = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
