[package]
name = "shrikedb-bin"
version.workspace = true
edition.workspace = true

[[bin]]
name = "shrikedb"
path = "src/main.rs"

[dependencies]
shrikedb-facade = { workspace = true }
shrikedb-persistence = { workspace = true }
shrikedb-server = { workspace = true }
mimalloc = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
