[package]
name = "shrikedb-server"
version.workspace = true
edition.workspace = true

[dependencies]
shrikedb-core = { workspace = true }
shrikedb-facade = { workspace = true }
shrikedb-persistence = { workspace = true }
ahash = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
